
---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 4
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: lualatex  
    toc: true
    toc_depth:  4   
    keep_tex:  true
    keep_md:   true
  header-includes:  
    -  \usepackage{helvet}  
    -  \renewcommand{\familydefault}{\sfdefault}  
    -  \usepackage{ulem}
fontsize: 10pt   
geometry: margin=0.4in,top=0.25in   
TAGS:  skeleton, httpuv
---
~/code/MASTER_INDEX.md

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      tidy = "styler",
                      error = TRUE,
                      collapse = T   ) # T easier to read
```

```
Starts http server on 127.0.0.1 port 5000

USAGE:   curl http://127.0.0.1  (CLI)
OR in browser:  http://127.0.0.1:5000/foo
```

```{r}
s <- startServer(host = "127.0.0.1", port = 5000,
  app = list(
    call = function(req) {
      body <- paste0("Time: ", Sys.time(), "<br>Path requested: ", req$PATH_INFO)
      list(
        status = 200L,
        headers = list('Content-Type' = 'text/html'),
        body = body
      )
    }
  )
)
s$stop()
```



```{r render, eval=FALSE, include=FALSE 	} 
output_dir  <- Sys.getenv("OUTPUT_DIR")
output_dir

{
# get file
file <- "/home/jim/.config/nvim/templates/skeleton.Rmd"
file  <- normalizePath(file)
file


## Ref only
    # the_dir  <- dirname(file)
    # file  <- basename(file)
    # file  <- file.path(the_dir, file)

}

rmarkdown::render(file,
#                  output_format="html_document",
                    output_format="pdf_document",
                    intermediates_dir='./tmp',
                    clean = F,              # leave tmp files
                    output_dir=output_dir
                  )
```

#### html ONLY (fonts)
```{r, results = 'asis',echo = F}
htmltools::h3("Test big font")
htmltools::h4('Test medium font')
htmltools::h5('Test smaller font')
```
`r htmltools::h3("Outside chunck")`
